/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chpc;

import java.util.Properties;

import chpc.database.PostgresDb;
import chpc.UI.MainUI;

public class App {
  public static void main(String[] args) {
    String dbUrl = "localhost:5432/nhpi";
    Properties props = new Properties();
    props.setProperty("user", "admin");
    props.setProperty("password", "admin");
    props.setProperty("ssl", "false");
    PostgresDb.initializeDb(dbUrl, props);

    MainUI.getInstance();
  }
}
